version: '2.0'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      # Used to create the DB when starting initially
      POSTGRES_DB: 'newchat'
      POSTGRES_USER: 'postgres'
      # Used by psql
      PGUSER: 'postgres'
      PGHOST: 'localhost'
      PGDATASE: 'newchat'

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./chamberofs:/code/
    restart: always
    depends_on:
      - db

  client:
    build: ./reactapp
    command: webpack-dev-server --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    volumes:
      - ./reactapp:/reactapp
    restart: always

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379